# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='am',
            field=models.PositiveIntegerField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guard',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='guard',
            name='childs',
            field=models.SmallIntegerField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guard',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='guard',
            name='fatherslastname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guard',
            name='fathersname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guard',
            name='marital',
            field=models.CharField(choices=[(b'e', b'Married'), (b'd', b'Divorced'), (b'u', b'Unmarried')], default=b'u', max_length=1),
        ),
        migrations.AddField(
            model_name='guard',
            name='mothersname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guard',
            name='telephone',
            field=models.PositiveIntegerField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
