# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guards', '0002_auto_20161008_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guard',
            name='afm',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='guard',
            name='ama',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='guard',
            name='amka',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='guard',
            name='employement',
            field=models.CharField(choices=[(b'f', b'Full'), (b'p', b'Part time')], default=b'f', max_length=1),
        ),
        migrations.AddField(
            model_name='guard',
            name='height',
            field=models.IntegerField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guard',
            name='identity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guard',
            name='licence_issue_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='guard',
            name='shoe',
            field=models.IntegerField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guard',
            name='weight',
            field=models.IntegerField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
