# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guards', '0003_auto_20161008_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guard',
            name='employement',
        ),
    ]
