# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guards', '0005_auto_20161008_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='gender',
            field=models.CharField(choices=[(b'm', b'Men'), (b'f', b'Female')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
