# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guards', '0007_guard_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guard',
            name='image',
        ),
    ]
